---
- name: Configure Nginx Load Balancer
  hosts: web1.ru-central1.internal
  become: yes

  tasks:
    - name: Configure nginx as load balancer
      copy:
        content: |
          upstream backend {
            server 192.168.20.13:80;  # web1
            server 192.168.30.25:80;  # web2
            least_conn;
          }

          server {
            listen 80;
            server_name _;

            location / {
              proxy_pass http://backend;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
        dest: /etc/nginx/sites-available/loadbalancer
      notify: restart nginx

    - name: Enable load balancer configuration
      file:
        src: /etc/nginx/sites-available/loadbalancer
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: yes
      notify: restart nginx

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
