---
- name: Install and Configure PostgreSQL
  hosts: web1.ru-central1.internal
  become: yes

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database and user manually
      shell: |
        sudo -u postgres psql -c "CREATE DATABASE myapp;"
        sudo -u postgres psql -c "CREATE USER myappuser WITH PASSWORD 'myapppass';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE myapp TO myappuser;"
      args:
        executable: /bin/bash
