---
- name: Install PostgreSQL
  hosts: web1.ru-central1.internal
  become: yes

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create application database
      become_user: postgres
      postgresql_db:
        name: myapp
        state: present

    - name: Create application user
      become_user: postgres
      postgresql_user:
        name: myappuser
        password: myapppass
        db: myapp
        state: present
        priv: ALL
